server:
  port: 8082
spring:
  datasource:
    driver-class-name: org.postgresql.Driver

ecommerce:
  auth:
    jwt:
      expiration:
        DOC_enabled: "Determines whether JWT tokens should expire or not"
        enabled: true
        DOC_expirationSecs: "600"
        expirationSecs: "600"
